### ISSUE TITLE
Money.Ecto.Map.Type.embed_as/2 should return :dump instead of :self

### ISSUE THREAD

**Issue by redrabbit** [kipcole9/money_sql#31]
When using a `Money.Ecto.Map.Type` in an an embedded schema, the parameterized type is not loading the price correctly:

```elixir
defmodule MyEmbed do
  embedded_schema do
    field(:price, Money.Ecto.Map.Type)
  end
end
```

Instead of loading the price through `Money.Ecto.Map.Type`, parsing the `:amount` with `Decimal.parse/1`, the field is loaded directly into a `Money` struct because the `embed_as/2` callback implementation return `:self`.

While this appears to be ok when the locale is set to English, it is not the case and somehow dangerous with locales that use a comma instead of a dot for pricing format:

```elixir
data = """
{
  "id": "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  "price": {
    "amount": "1.85",
    "currency": "CHF"
  }
}
"""

MyCldr.put_locale(:en)

Ecto.embedded_load(MyEmbed, Jason.decode!(data), :json)
```

returns CHF `1.85`

```elixir
%MyEmbed{
  id: "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  price: Money.new(:CHF, "1.85"),
}
```

but when changing the locale to German for example, things don't go as excepted:

```elixir
MyCldr.put_locale(:de)

Ecto.embedded_load(MyEmbed, Jason.decode!(data), :json)
```

returns CHF `185`

```elixir
%MyEmbed{
  id: "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  price: Money.new(:CHF, "185"),
}
```

Changing the `Money.Ecto.Map.Type.embed_as/2` to return `:dump` instead of `:self` fixes the issue and forces the data to be loaded through `Money.Ecto.Map.Type.load/2`.

Not sure if this is also the case with `Money.Ecto.Composite.Type`. But I assume this has the same issue and also need to return `:dump` instead of `:self`.

**Comment by kipcole9** [comment]
Mario, truly appreciated, thanks for raising an issue. Clearly not good. And it shows how little I understand embedded schemas.I will work on this tonight in my timezone (currently UTC+10).Do you happy to have a failing test case you might be able to provide?I don’t think this affect the composite type since that won’t even work in an embedded schema.Sent from my iPhoneOn 14 Jun 2023, at 02:20, Mario Flach ***@***.***> wrote:﻿
When using a Money.Ecto.Map.Type in an an embedded schema, the parameterized type is not loading the price correctly:
defmodule MyEmbed do
  embedded_schema do
    field(:price, Money.Ecto.Map.Type)
  end
end
Instead of loading the price through Money.Ecto.Map.Type, parsing the :amount with Decimal.parse/1, the field is loaded directly into a Money struct because the embed_as/2 callback implementation return :self.
While this appears to be ok when the locale is set to English, it is not the case and somehow dangerous with locales that use a comma instead of a dot for pricing format:
data = """
{
  "id": "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  "price": {
    "amount": "1.85",
    "currency": "CHF"
  }
}
"""

MyCldr.put_locale(:en)

Ecto.embedded_load(MyEmbed, Jason.decode!(data), :json)
returns CHF 1.85
%MyEmbed{
  id: "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  price: Money.new(:CHF, "1.85"),
}
but when changing the locale to German for example, things don't go as excepted:
MyCldr.put_locale(:de)

Ecto.embedded_load(MyEmbed, Jason.decode!(data), :json)
returns CHF 185
%MyEmbed{
  id: "431ab887-69a9-4fc6-85d4-3c0b83f8e2ed",
  price: Money.new(:CHF, "185"),
}
Changing the Money.Ecto.Map.Type.embed_as/2 to return :dump instead of :self fixes the issue and forces the data to be loaded through Money.Ecto.Map.Type.load/2.
Not sure if this is also the case with Money.Ecto.Composite.Type. But I assume this has the same issue and also need to return :dump instead of :self.

**Comment by redrabbit** [comment]
👋 @kipcole9 and thank you for the prompt answer!

I wrote a PR fixing the issue and added 2 tests for testing casting, dumping and loading with embedded schemas.
Hope this helps.
